export const SET_TOOL = 'SET_TOOL';
export const SET_PALETTE_MODE = 'SET_PALETTE_MODE'

export const BUILDER_SELECT_PALETTE_ITEM = 'BUILDER_SELECT_PALETTE_ITEM'
export const BUILDER_SET_ACTIVE_LAYER = 'BUILDER_SET_ACTIVE_LAYER'
export const BUILDER_SET_MOUSE_POSITION = 'BUILDER_SET_MOUSE_POSITION'
export const BUILDER_SET_PAPER_VIEW_LOADED = 'BUILDER_SET_PAPER_VIEW_LOADED'

export const LAYOUT_ADD_ITEM = 'LAYOUT_ADD_ITEM'
export const LAYOUT_UPDATE_ITEM = 'LAYOUT_UPDATE_ITEM'
export const LAYOUT_REMOVE_ITEM = 'LAYOUT_REMOVE_ITEM'
export const LAYOUT_SET_LAYERS = 'LAYOUT_SET_LAYERS'
export const LAYOUT_SET_LAYER_VISIBLE = 'LAYOUT_SET_LAYER_VISIBLE'
