export const SET_TOOL = 'SET_TOOL';
export const SET_ACTIVE_LAYER = 'SET_ACTIVE_LAYER'
export const SET_LAYER_VISIBLE = 'SET_LAYER_VISIBLE'
export const SELECT_PALETTE_ITEM = 'SELECT_PALETTE_ITEM'
export const SET_PALETTE_MODE = 'SET_PALETTE_MODE'
export const UPDATE_LAST_SELECTED_ITEMS = 'UPDATE_LAST_SELECTED_ITEMS'

